'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace UserAPI
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="cSMT_ATJ_User_Lite", [Namespace]:="http://runuh.com/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class cSMT_ATJ_User_Lite
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsernameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="eAlentejoAPIResultCode", [Namespace]:="http://runuh.com/")>  _
    Public Enum eAlentejoAPIResultCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        GenericFailure = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="cSMT_ATJ_User", [Namespace]:="http://runuh.com/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class cSMT_ATJ_User
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SCHEMA_VERSIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Created_UTCTicksField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastLogin_UTCTicksField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Balance_EncryptedField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsernameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordHashField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimezoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastLoginIpAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Address1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Address2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Address3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PostalCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhoneOfficeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhoneMobileField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WebsiteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PayPalAccountEmailAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailNotificationLevelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumberOfCoresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RenderLevelsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MaxRenderingTimeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MaxCostField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OutputTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RenderEngineField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AccountStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AccountTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BillingTypeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SCHEMA_VERSION() As String
            Get
                Return Me.SCHEMA_VERSIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SCHEMA_VERSIONField, value) <> true) Then
                    Me.SCHEMA_VERSIONField = value
                    Me.RaisePropertyChanged("SCHEMA_VERSION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Created_UTCTicks() As String
            Get
                Return Me.Created_UTCTicksField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Created_UTCTicksField, value) <> true) Then
                    Me.Created_UTCTicksField = value
                    Me.RaisePropertyChanged("Created_UTCTicks")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property LastLogin_UTCTicks() As String
            Get
                Return Me.LastLogin_UTCTicksField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastLogin_UTCTicksField, value) <> true) Then
                    Me.LastLogin_UTCTicksField = value
                    Me.RaisePropertyChanged("LastLogin_UTCTicks")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Balance_Encrypted() As String
            Get
                Return Me.Balance_EncryptedField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Balance_EncryptedField, value) <> true) Then
                    Me.Balance_EncryptedField = value
                    Me.RaisePropertyChanged("Balance_Encrypted")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property PasswordHash() As String
            Get
                Return Me.PasswordHashField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordHashField, value) <> true) Then
                    Me.PasswordHashField = value
                    Me.RaisePropertyChanged("PasswordHash")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Timezone() As String
            Get
                Return Me.TimezoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimezoneField, value) <> true) Then
                    Me.TimezoneField = value
                    Me.RaisePropertyChanged("Timezone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property LastLoginIpAddress() As String
            Get
                Return Me.LastLoginIpAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastLoginIpAddressField, value) <> true) Then
                    Me.LastLoginIpAddressField = value
                    Me.RaisePropertyChanged("LastLoginIpAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property Address1() As String
            Get
                Return Me.Address1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Address1Field, value) <> true) Then
                    Me.Address1Field = value
                    Me.RaisePropertyChanged("Address1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property Address2() As String
            Get
                Return Me.Address2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Address2Field, value) <> true) Then
                    Me.Address2Field = value
                    Me.RaisePropertyChanged("Address2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property Address3() As String
            Get
                Return Me.Address3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Address3Field, value) <> true) Then
                    Me.Address3Field = value
                    Me.RaisePropertyChanged("Address3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property PostalCode() As String
            Get
                Return Me.PostalCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostalCodeField, value) <> true) Then
                    Me.PostalCodeField = value
                    Me.RaisePropertyChanged("PostalCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Property Country() As String
            Get
                Return Me.CountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryField, value) <> true) Then
                    Me.CountryField = value
                    Me.RaisePropertyChanged("Country")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=19)>  _
        Public Property EmailAddress() As String
            Get
                Return Me.EmailAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailAddressField, value) <> true) Then
                    Me.EmailAddressField = value
                    Me.RaisePropertyChanged("EmailAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=20)>  _
        Public Property PhoneOffice() As String
            Get
                Return Me.PhoneOfficeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneOfficeField, value) <> true) Then
                    Me.PhoneOfficeField = value
                    Me.RaisePropertyChanged("PhoneOffice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=21)>  _
        Public Property PhoneMobile() As String
            Get
                Return Me.PhoneMobileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneMobileField, value) <> true) Then
                    Me.PhoneMobileField = value
                    Me.RaisePropertyChanged("PhoneMobile")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public Property Website() As String
            Get
                Return Me.WebsiteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WebsiteField, value) <> true) Then
                    Me.WebsiteField = value
                    Me.RaisePropertyChanged("Website")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=23)>  _
        Public Property PayPalAccountEmailAddress() As String
            Get
                Return Me.PayPalAccountEmailAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PayPalAccountEmailAddressField, value) <> true) Then
                    Me.PayPalAccountEmailAddressField = value
                    Me.RaisePropertyChanged("PayPalAccountEmailAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=24)>  _
        Public Property EmailNotificationLevel() As String
            Get
                Return Me.EmailNotificationLevelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailNotificationLevelField, value) <> true) Then
                    Me.EmailNotificationLevelField = value
                    Me.RaisePropertyChanged("EmailNotificationLevel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=25)>  _
        Public Property NumberOfCores() As String
            Get
                Return Me.NumberOfCoresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumberOfCoresField, value) <> true) Then
                    Me.NumberOfCoresField = value
                    Me.RaisePropertyChanged("NumberOfCores")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=26)>  _
        Public Property RenderLevels() As String
            Get
                Return Me.RenderLevelsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RenderLevelsField, value) <> true) Then
                    Me.RenderLevelsField = value
                    Me.RaisePropertyChanged("RenderLevels")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=27)>  _
        Public Property MaxRenderingTime() As String
            Get
                Return Me.MaxRenderingTimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MaxRenderingTimeField, value) <> true) Then
                    Me.MaxRenderingTimeField = value
                    Me.RaisePropertyChanged("MaxRenderingTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=28)>  _
        Public Property MaxCost() As String
            Get
                Return Me.MaxCostField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MaxCostField, value) <> true) Then
                    Me.MaxCostField = value
                    Me.RaisePropertyChanged("MaxCost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=29)>  _
        Public Property OutputType() As String
            Get
                Return Me.OutputTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OutputTypeField, value) <> true) Then
                    Me.OutputTypeField = value
                    Me.RaisePropertyChanged("OutputType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=30)>  _
        Public Property RenderEngine() As String
            Get
                Return Me.RenderEngineField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RenderEngineField, value) <> true) Then
                    Me.RenderEngineField = value
                    Me.RaisePropertyChanged("RenderEngine")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=31)>  _
        Public Property AccountStatus() As String
            Get
                Return Me.AccountStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountStatusField, value) <> true) Then
                    Me.AccountStatusField = value
                    Me.RaisePropertyChanged("AccountStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=32)>  _
        Public Property AccountType() As String
            Get
                Return Me.AccountTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountTypeField, value) <> true) Then
                    Me.AccountTypeField = value
                    Me.RaisePropertyChanged("AccountType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=33)>  _
        Public Property BillingType() As String
            Get
                Return Me.BillingTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BillingTypeField, value) <> true) Then
                    Me.BillingTypeField = value
                    Me.RaisePropertyChanged("BillingType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://runuh.com/", ConfigurationName:="UserAPI.UserAPISoap")>  _
    Public Interface UserAPISoap
        
        'CODEGEN: Generating message contract since element name SessionToken from namespace http://runuh.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://runuh.com/GetUserInfoLite", ReplyAction:="*")>  _
        Function GetUserInfoLite(ByVal request As UserAPI.GetUserInfoLiteRequest) As UserAPI.GetUserInfoLiteResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://runuh.com/GetUserInfoLite", ReplyAction:="*")>  _
        Function BeginGetUserInfoLite(ByVal request As UserAPI.GetUserInfoLiteRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetUserInfoLite(ByVal result As System.IAsyncResult) As UserAPI.GetUserInfoLiteResponse
        
        'CODEGEN: Generating message contract since element name SessionToken from namespace http://runuh.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://runuh.com/GetUserCredit", ReplyAction:="*")>  _
        Function GetUserCredit(ByVal request As UserAPI.GetUserCreditRequest) As UserAPI.GetUserCreditResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://runuh.com/GetUserCredit", ReplyAction:="*")>  _
        Function BeginGetUserCredit(ByVal request As UserAPI.GetUserCreditRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetUserCredit(ByVal result As System.IAsyncResult) As UserAPI.GetUserCreditResponse
        
        'CODEGEN: Generating message contract since element name SessionToken from namespace http://runuh.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://runuh.com/GetAddCreditUrl", ReplyAction:="*")>  _
        Function GetAddCreditUrl(ByVal request As UserAPI.GetAddCreditUrlRequest) As UserAPI.GetAddCreditUrlResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://runuh.com/GetAddCreditUrl", ReplyAction:="*")>  _
        Function BeginGetAddCreditUrl(ByVal request As UserAPI.GetAddCreditUrlRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetAddCreditUrl(ByVal result As System.IAsyncResult) As UserAPI.GetAddCreditUrlResponse
        
        'CODEGEN: Generating message contract since element name SessionToken from namespace http://runuh.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://runuh.com/ModifyUserProperties", ReplyAction:="*")>  _
        Function ModifyUserProperties(ByVal request As UserAPI.ModifyUserPropertiesRequest) As UserAPI.ModifyUserPropertiesResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://runuh.com/ModifyUserProperties", ReplyAction:="*")>  _
        Function BeginModifyUserProperties(ByVal request As UserAPI.ModifyUserPropertiesRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndModifyUserProperties(ByVal result As System.IAsyncResult) As UserAPI.ModifyUserPropertiesResponse
        
        'CODEGEN: Generating message contract since element name Username from namespace http://runuh.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://runuh.com/UsernameExists", ReplyAction:="*")>  _
        Function UsernameExists(ByVal request As UserAPI.UsernameExistsRequest) As UserAPI.UsernameExistsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://runuh.com/UsernameExists", ReplyAction:="*")>  _
        Function BeginUsernameExists(ByVal request As UserAPI.UsernameExistsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndUsernameExists(ByVal result As System.IAsyncResult) As UserAPI.UsernameExistsResponse
        
        'CODEGEN: Generating message contract since element name User from namespace http://runuh.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://runuh.com/Signup", ReplyAction:="*")>  _
        Function Signup(ByVal request As UserAPI.SignupRequest) As UserAPI.SignupResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://runuh.com/Signup", ReplyAction:="*")>  _
        Function BeginSignup(ByVal request As UserAPI.SignupRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSignup(ByVal result As System.IAsyncResult) As UserAPI.SignupResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUserInfoLiteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserInfoLite", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.GetUserInfoLiteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.GetUserInfoLiteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class GetUserInfoLiteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SessionToken As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SessionToken As String, ByVal Username As String, ByVal outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite)
            MyBase.New
            Me.SessionToken = SessionToken
            Me.Username = Username
            Me.outLiteUserInfo = outLiteUserInfo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUserInfoLiteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserInfoLiteResponse", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.GetUserInfoLiteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.GetUserInfoLiteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class GetUserInfoLiteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetUserInfoLiteResult As UserAPI.eAlentejoAPIResultCode
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUserInfoLiteResult As UserAPI.eAlentejoAPIResultCode, ByVal outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite)
            MyBase.New
            Me.GetUserInfoLiteResult = GetUserInfoLiteResult
            Me.outLiteUserInfo = outLiteUserInfo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUserCreditRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserCredit", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.GetUserCreditRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.GetUserCreditRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class GetUserCreditRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SessionToken As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public UserId As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public outUserCredit As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SessionToken As String, ByVal UserId As String, ByVal outUserCredit As Double)
            MyBase.New
            Me.SessionToken = SessionToken
            Me.UserId = UserId
            Me.outUserCredit = outUserCredit
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUserCreditResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserCreditResponse", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.GetUserCreditResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.GetUserCreditResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class GetUserCreditResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetUserCreditResult As UserAPI.eAlentejoAPIResultCode
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public outUserCredit As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUserCreditResult As UserAPI.eAlentejoAPIResultCode, ByVal outUserCredit As Double)
            MyBase.New
            Me.GetUserCreditResult = GetUserCreditResult
            Me.outUserCredit = outUserCredit
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAddCreditUrlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAddCreditUrl", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.GetAddCreditUrlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.GetAddCreditUrlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class GetAddCreditUrlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SessionToken As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public AmountToAdd As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public outUrl As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SessionToken As String, ByVal AmountToAdd As Double, ByVal outUrl As String)
            MyBase.New
            Me.SessionToken = SessionToken
            Me.AmountToAdd = AmountToAdd
            Me.outUrl = outUrl
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAddCreditUrlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAddCreditUrlResponse", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.GetAddCreditUrlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.GetAddCreditUrlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class GetAddCreditUrlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetAddCreditUrlResult As UserAPI.eAlentejoAPIResultCode
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public outUrl As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAddCreditUrlResult As UserAPI.eAlentejoAPIResultCode, ByVal outUrl As String)
            MyBase.New
            Me.GetAddCreditUrlResult = GetAddCreditUrlResult
            Me.outUrl = outUrl
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ModifyUserPropertiesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ModifyUserProperties", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.ModifyUserPropertiesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.ModifyUserPropertiesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class ModifyUserPropertiesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SessionToken As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NewProperties As UserAPI.cSMT_ATJ_User
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SessionToken As String, ByVal NewProperties As UserAPI.cSMT_ATJ_User)
            MyBase.New
            Me.SessionToken = SessionToken
            Me.NewProperties = NewProperties
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ModifyUserPropertiesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ModifyUserPropertiesResponse", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.ModifyUserPropertiesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.ModifyUserPropertiesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class ModifyUserPropertiesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ModifyUserPropertiesResult As UserAPI.eAlentejoAPIResultCode
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ModifyUserPropertiesResult As UserAPI.eAlentejoAPIResultCode)
            MyBase.New
            Me.ModifyUserPropertiesResult = ModifyUserPropertiesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UsernameExistsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UsernameExists", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.UsernameExistsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.UsernameExistsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class UsernameExistsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public outExists As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Username As String, ByVal outExists As Boolean)
            MyBase.New
            Me.Username = Username
            Me.outExists = outExists
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UsernameExistsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UsernameExistsResponse", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.UsernameExistsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.UsernameExistsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class UsernameExistsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public UsernameExistsResult As UserAPI.eAlentejoAPIResultCode
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public outExists As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UsernameExistsResult As UserAPI.eAlentejoAPIResultCode, ByVal outExists As Boolean)
            MyBase.New
            Me.UsernameExistsResult = UsernameExistsResult
            Me.outExists = outExists
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SignupRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Signup", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.SignupRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.SignupRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class SignupRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public User As UserAPI.cSMT_ATJ_User
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public outNewUserId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal User As UserAPI.cSMT_ATJ_User, ByVal outNewUserId As String)
            MyBase.New
            Me.User = User
            Me.outNewUserId = outNewUserId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SignupResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SignupResponse", [Namespace]:="http://runuh.com/", Order:=0)>  _
        Public Body As UserAPI.SignupResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UserAPI.SignupResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://runuh.com/")>  _
    Partial Public Class SignupResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public SignupResult As UserAPI.eAlentejoAPIResultCode
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public outNewUserId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SignupResult As UserAPI.eAlentejoAPIResultCode, ByVal outNewUserId As String)
            MyBase.New
            Me.SignupResult = SignupResult
            Me.outNewUserId = outNewUserId
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface UserAPISoapChannel
        Inherits UserAPI.UserAPISoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetUserInfoLiteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property outLiteUserInfo() As UserAPI.cSMT_ATJ_User_Lite
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),UserAPI.cSMT_ATJ_User_Lite)
            End Get
        End Property
        
        Public ReadOnly Property Result() As UserAPI.eAlentejoAPIResultCode
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),UserAPI.eAlentejoAPIResultCode)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetUserCreditCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property outUserCredit() As Double
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
        
        Public ReadOnly Property Result() As UserAPI.eAlentejoAPIResultCode
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),UserAPI.eAlentejoAPIResultCode)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetAddCreditUrlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property outUrl() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        Public ReadOnly Property Result() As UserAPI.eAlentejoAPIResultCode
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),UserAPI.eAlentejoAPIResultCode)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ModifyUserPropertiesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As UserAPI.eAlentejoAPIResultCode
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),UserAPI.eAlentejoAPIResultCode)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UsernameExistsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property outExists() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        Public ReadOnly Property Result() As UserAPI.eAlentejoAPIResultCode
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),UserAPI.eAlentejoAPIResultCode)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SignupCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property outNewUserId() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        Public ReadOnly Property Result() As UserAPI.eAlentejoAPIResultCode
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),UserAPI.eAlentejoAPIResultCode)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UserAPISoapClient
        Inherits System.ServiceModel.ClientBase(Of UserAPI.UserAPISoap)
        Implements UserAPI.UserAPISoap
        
        Private onBeginGetUserInfoLiteDelegate As BeginOperationDelegate
        
        Private onEndGetUserInfoLiteDelegate As EndOperationDelegate
        
        Private onGetUserInfoLiteCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetUserCreditDelegate As BeginOperationDelegate
        
        Private onEndGetUserCreditDelegate As EndOperationDelegate
        
        Private onGetUserCreditCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetAddCreditUrlDelegate As BeginOperationDelegate
        
        Private onEndGetAddCreditUrlDelegate As EndOperationDelegate
        
        Private onGetAddCreditUrlCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginModifyUserPropertiesDelegate As BeginOperationDelegate
        
        Private onEndModifyUserPropertiesDelegate As EndOperationDelegate
        
        Private onModifyUserPropertiesCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginUsernameExistsDelegate As BeginOperationDelegate
        
        Private onEndUsernameExistsDelegate As EndOperationDelegate
        
        Private onUsernameExistsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSignupDelegate As BeginOperationDelegate
        
        Private onEndSignupDelegate As EndOperationDelegate
        
        Private onSignupCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event GetUserInfoLiteCompleted As System.EventHandler(Of GetUserInfoLiteCompletedEventArgs)
        
        Public Event GetUserCreditCompleted As System.EventHandler(Of GetUserCreditCompletedEventArgs)
        
        Public Event GetAddCreditUrlCompleted As System.EventHandler(Of GetAddCreditUrlCompletedEventArgs)
        
        Public Event ModifyUserPropertiesCompleted As System.EventHandler(Of ModifyUserPropertiesCompletedEventArgs)
        
        Public Event UsernameExistsCompleted As System.EventHandler(Of UsernameExistsCompletedEventArgs)
        
        Public Event SignupCompleted As System.EventHandler(Of SignupCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_GetUserInfoLite(ByVal request As UserAPI.GetUserInfoLiteRequest) As UserAPI.GetUserInfoLiteResponse Implements UserAPI.UserAPISoap.GetUserInfoLite
            Return MyBase.Channel.GetUserInfoLite(request)
        End Function
        
        Public Function GetUserInfoLite(ByVal SessionToken As String, ByVal Username As String, ByRef outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite) As UserAPI.eAlentejoAPIResultCode
            Dim inValue As UserAPI.GetUserInfoLiteRequest = New UserAPI.GetUserInfoLiteRequest()
            inValue.Body = New UserAPI.GetUserInfoLiteRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.Username = Username
            inValue.Body.outLiteUserInfo = outLiteUserInfo
            Dim retVal As UserAPI.GetUserInfoLiteResponse = CType(Me,UserAPI.UserAPISoap).GetUserInfoLite(inValue)
            outLiteUserInfo = retVal.Body.outLiteUserInfo
            Return retVal.Body.GetUserInfoLiteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_BeginGetUserInfoLite(ByVal request As UserAPI.GetUserInfoLiteRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserAPI.UserAPISoap.BeginGetUserInfoLite
            Return MyBase.Channel.BeginGetUserInfoLite(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginGetUserInfoLite(ByVal SessionToken As String, ByVal Username As String, ByVal outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As UserAPI.GetUserInfoLiteRequest = New UserAPI.GetUserInfoLiteRequest()
            inValue.Body = New UserAPI.GetUserInfoLiteRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.Username = Username
            inValue.Body.outLiteUserInfo = outLiteUserInfo
            Return CType(Me,UserAPI.UserAPISoap).BeginGetUserInfoLite(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_EndGetUserInfoLite(ByVal result As System.IAsyncResult) As UserAPI.GetUserInfoLiteResponse Implements UserAPI.UserAPISoap.EndGetUserInfoLite
            Return MyBase.Channel.EndGetUserInfoLite(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndGetUserInfoLite(ByVal result As System.IAsyncResult, <System.Runtime.InteropServices.OutAttribute()> ByRef outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite) As UserAPI.eAlentejoAPIResultCode
            Dim retVal As UserAPI.GetUserInfoLiteResponse = CType(Me,UserAPI.UserAPISoap).EndGetUserInfoLite(result)
            outLiteUserInfo = retVal.Body.outLiteUserInfo
            Return retVal.Body.GetUserInfoLiteResult
        End Function
        
        Private Function OnBeginGetUserInfoLite(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim SessionToken As String = CType(inValues(0),String)
            Dim Username As String = CType(inValues(1),String)
            Dim outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite = CType(inValues(2),UserAPI.cSMT_ATJ_User_Lite)
            Return Me.BeginGetUserInfoLite(SessionToken, Username, outLiteUserInfo, callback, asyncState)
        End Function
        
        Private Function OnEndGetUserInfoLite(ByVal result As System.IAsyncResult) As Object()
            Dim outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite = Me.GetDefaultValueForInitialization(Of UserAPI.cSMT_ATJ_User_Lite)
            Dim retVal As UserAPI.eAlentejoAPIResultCode = Me.EndGetUserInfoLite(result, outLiteUserInfo)
            Return New Object() {outLiteUserInfo, retVal}
        End Function
        
        Private Sub OnGetUserInfoLiteCompleted(ByVal state As Object)
            If (Not (Me.GetUserInfoLiteCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetUserInfoLiteCompleted(Me, New GetUserInfoLiteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetUserInfoLiteAsync(ByVal SessionToken As String, ByVal Username As String, ByVal outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite)
            Me.GetUserInfoLiteAsync(SessionToken, Username, outLiteUserInfo, Nothing)
        End Sub
        
        Public Overloads Sub GetUserInfoLiteAsync(ByVal SessionToken As String, ByVal Username As String, ByVal outLiteUserInfo As UserAPI.cSMT_ATJ_User_Lite, ByVal userState As Object)
            If (Me.onBeginGetUserInfoLiteDelegate Is Nothing) Then
                Me.onBeginGetUserInfoLiteDelegate = AddressOf Me.OnBeginGetUserInfoLite
            End If
            If (Me.onEndGetUserInfoLiteDelegate Is Nothing) Then
                Me.onEndGetUserInfoLiteDelegate = AddressOf Me.OnEndGetUserInfoLite
            End If
            If (Me.onGetUserInfoLiteCompletedDelegate Is Nothing) Then
                Me.onGetUserInfoLiteCompletedDelegate = AddressOf Me.OnGetUserInfoLiteCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetUserInfoLiteDelegate, New Object() {SessionToken, Username, outLiteUserInfo}, Me.onEndGetUserInfoLiteDelegate, Me.onGetUserInfoLiteCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_GetUserCredit(ByVal request As UserAPI.GetUserCreditRequest) As UserAPI.GetUserCreditResponse Implements UserAPI.UserAPISoap.GetUserCredit
            Return MyBase.Channel.GetUserCredit(request)
        End Function
        
        Public Function GetUserCredit(ByVal SessionToken As String, ByVal UserId As String, ByRef outUserCredit As Double) As UserAPI.eAlentejoAPIResultCode
            Dim inValue As UserAPI.GetUserCreditRequest = New UserAPI.GetUserCreditRequest()
            inValue.Body = New UserAPI.GetUserCreditRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.UserId = UserId
            inValue.Body.outUserCredit = outUserCredit
            Dim retVal As UserAPI.GetUserCreditResponse = CType(Me,UserAPI.UserAPISoap).GetUserCredit(inValue)
            outUserCredit = retVal.Body.outUserCredit
            Return retVal.Body.GetUserCreditResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_BeginGetUserCredit(ByVal request As UserAPI.GetUserCreditRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserAPI.UserAPISoap.BeginGetUserCredit
            Return MyBase.Channel.BeginGetUserCredit(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginGetUserCredit(ByVal SessionToken As String, ByVal UserId As String, ByVal outUserCredit As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As UserAPI.GetUserCreditRequest = New UserAPI.GetUserCreditRequest()
            inValue.Body = New UserAPI.GetUserCreditRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.UserId = UserId
            inValue.Body.outUserCredit = outUserCredit
            Return CType(Me,UserAPI.UserAPISoap).BeginGetUserCredit(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_EndGetUserCredit(ByVal result As System.IAsyncResult) As UserAPI.GetUserCreditResponse Implements UserAPI.UserAPISoap.EndGetUserCredit
            Return MyBase.Channel.EndGetUserCredit(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndGetUserCredit(ByVal result As System.IAsyncResult, <System.Runtime.InteropServices.OutAttribute()> ByRef outUserCredit As Double) As UserAPI.eAlentejoAPIResultCode
            Dim retVal As UserAPI.GetUserCreditResponse = CType(Me,UserAPI.UserAPISoap).EndGetUserCredit(result)
            outUserCredit = retVal.Body.outUserCredit
            Return retVal.Body.GetUserCreditResult
        End Function
        
        Private Function OnBeginGetUserCredit(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim SessionToken As String = CType(inValues(0),String)
            Dim UserId As String = CType(inValues(1),String)
            Dim outUserCredit As Double = CType(inValues(2),Double)
            Return Me.BeginGetUserCredit(SessionToken, UserId, outUserCredit, callback, asyncState)
        End Function
        
        Private Function OnEndGetUserCredit(ByVal result As System.IAsyncResult) As Object()
            Dim outUserCredit As Double = Me.GetDefaultValueForInitialization(Of Double)
            Dim retVal As UserAPI.eAlentejoAPIResultCode = Me.EndGetUserCredit(result, outUserCredit)
            Return New Object() {outUserCredit, retVal}
        End Function
        
        Private Sub OnGetUserCreditCompleted(ByVal state As Object)
            If (Not (Me.GetUserCreditCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetUserCreditCompleted(Me, New GetUserCreditCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetUserCreditAsync(ByVal SessionToken As String, ByVal UserId As String, ByVal outUserCredit As Double)
            Me.GetUserCreditAsync(SessionToken, UserId, outUserCredit, Nothing)
        End Sub
        
        Public Overloads Sub GetUserCreditAsync(ByVal SessionToken As String, ByVal UserId As String, ByVal outUserCredit As Double, ByVal userState As Object)
            If (Me.onBeginGetUserCreditDelegate Is Nothing) Then
                Me.onBeginGetUserCreditDelegate = AddressOf Me.OnBeginGetUserCredit
            End If
            If (Me.onEndGetUserCreditDelegate Is Nothing) Then
                Me.onEndGetUserCreditDelegate = AddressOf Me.OnEndGetUserCredit
            End If
            If (Me.onGetUserCreditCompletedDelegate Is Nothing) Then
                Me.onGetUserCreditCompletedDelegate = AddressOf Me.OnGetUserCreditCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetUserCreditDelegate, New Object() {SessionToken, UserId, outUserCredit}, Me.onEndGetUserCreditDelegate, Me.onGetUserCreditCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_GetAddCreditUrl(ByVal request As UserAPI.GetAddCreditUrlRequest) As UserAPI.GetAddCreditUrlResponse Implements UserAPI.UserAPISoap.GetAddCreditUrl
            Return MyBase.Channel.GetAddCreditUrl(request)
        End Function
        
        Public Function GetAddCreditUrl(ByVal SessionToken As String, ByVal AmountToAdd As Double, ByRef outUrl As String) As UserAPI.eAlentejoAPIResultCode
            Dim inValue As UserAPI.GetAddCreditUrlRequest = New UserAPI.GetAddCreditUrlRequest()
            inValue.Body = New UserAPI.GetAddCreditUrlRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.AmountToAdd = AmountToAdd
            inValue.Body.outUrl = outUrl
            Dim retVal As UserAPI.GetAddCreditUrlResponse = CType(Me,UserAPI.UserAPISoap).GetAddCreditUrl(inValue)
            outUrl = retVal.Body.outUrl
            Return retVal.Body.GetAddCreditUrlResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_BeginGetAddCreditUrl(ByVal request As UserAPI.GetAddCreditUrlRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserAPI.UserAPISoap.BeginGetAddCreditUrl
            Return MyBase.Channel.BeginGetAddCreditUrl(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginGetAddCreditUrl(ByVal SessionToken As String, ByVal AmountToAdd As Double, ByVal outUrl As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As UserAPI.GetAddCreditUrlRequest = New UserAPI.GetAddCreditUrlRequest()
            inValue.Body = New UserAPI.GetAddCreditUrlRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.AmountToAdd = AmountToAdd
            inValue.Body.outUrl = outUrl
            Return CType(Me,UserAPI.UserAPISoap).BeginGetAddCreditUrl(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_EndGetAddCreditUrl(ByVal result As System.IAsyncResult) As UserAPI.GetAddCreditUrlResponse Implements UserAPI.UserAPISoap.EndGetAddCreditUrl
            Return MyBase.Channel.EndGetAddCreditUrl(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndGetAddCreditUrl(ByVal result As System.IAsyncResult, <System.Runtime.InteropServices.OutAttribute()> ByRef outUrl As String) As UserAPI.eAlentejoAPIResultCode
            Dim retVal As UserAPI.GetAddCreditUrlResponse = CType(Me,UserAPI.UserAPISoap).EndGetAddCreditUrl(result)
            outUrl = retVal.Body.outUrl
            Return retVal.Body.GetAddCreditUrlResult
        End Function
        
        Private Function OnBeginGetAddCreditUrl(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim SessionToken As String = CType(inValues(0),String)
            Dim AmountToAdd As Double = CType(inValues(1),Double)
            Dim outUrl As String = CType(inValues(2),String)
            Return Me.BeginGetAddCreditUrl(SessionToken, AmountToAdd, outUrl, callback, asyncState)
        End Function
        
        Private Function OnEndGetAddCreditUrl(ByVal result As System.IAsyncResult) As Object()
            Dim outUrl As String = Me.GetDefaultValueForInitialization(Of String)
            Dim retVal As UserAPI.eAlentejoAPIResultCode = Me.EndGetAddCreditUrl(result, outUrl)
            Return New Object() {outUrl, retVal}
        End Function
        
        Private Sub OnGetAddCreditUrlCompleted(ByVal state As Object)
            If (Not (Me.GetAddCreditUrlCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetAddCreditUrlCompleted(Me, New GetAddCreditUrlCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetAddCreditUrlAsync(ByVal SessionToken As String, ByVal AmountToAdd As Double, ByVal outUrl As String)
            Me.GetAddCreditUrlAsync(SessionToken, AmountToAdd, outUrl, Nothing)
        End Sub
        
        Public Overloads Sub GetAddCreditUrlAsync(ByVal SessionToken As String, ByVal AmountToAdd As Double, ByVal outUrl As String, ByVal userState As Object)
            If (Me.onBeginGetAddCreditUrlDelegate Is Nothing) Then
                Me.onBeginGetAddCreditUrlDelegate = AddressOf Me.OnBeginGetAddCreditUrl
            End If
            If (Me.onEndGetAddCreditUrlDelegate Is Nothing) Then
                Me.onEndGetAddCreditUrlDelegate = AddressOf Me.OnEndGetAddCreditUrl
            End If
            If (Me.onGetAddCreditUrlCompletedDelegate Is Nothing) Then
                Me.onGetAddCreditUrlCompletedDelegate = AddressOf Me.OnGetAddCreditUrlCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetAddCreditUrlDelegate, New Object() {SessionToken, AmountToAdd, outUrl}, Me.onEndGetAddCreditUrlDelegate, Me.onGetAddCreditUrlCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_ModifyUserProperties(ByVal request As UserAPI.ModifyUserPropertiesRequest) As UserAPI.ModifyUserPropertiesResponse Implements UserAPI.UserAPISoap.ModifyUserProperties
            Return MyBase.Channel.ModifyUserProperties(request)
        End Function
        
        Public Function ModifyUserProperties(ByVal SessionToken As String, ByVal NewProperties As UserAPI.cSMT_ATJ_User) As UserAPI.eAlentejoAPIResultCode
            Dim inValue As UserAPI.ModifyUserPropertiesRequest = New UserAPI.ModifyUserPropertiesRequest()
            inValue.Body = New UserAPI.ModifyUserPropertiesRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.NewProperties = NewProperties
            Dim retVal As UserAPI.ModifyUserPropertiesResponse = CType(Me,UserAPI.UserAPISoap).ModifyUserProperties(inValue)
            Return retVal.Body.ModifyUserPropertiesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_BeginModifyUserProperties(ByVal request As UserAPI.ModifyUserPropertiesRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserAPI.UserAPISoap.BeginModifyUserProperties
            Return MyBase.Channel.BeginModifyUserProperties(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginModifyUserProperties(ByVal SessionToken As String, ByVal NewProperties As UserAPI.cSMT_ATJ_User, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As UserAPI.ModifyUserPropertiesRequest = New UserAPI.ModifyUserPropertiesRequest()
            inValue.Body = New UserAPI.ModifyUserPropertiesRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.NewProperties = NewProperties
            Return CType(Me,UserAPI.UserAPISoap).BeginModifyUserProperties(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_EndModifyUserProperties(ByVal result As System.IAsyncResult) As UserAPI.ModifyUserPropertiesResponse Implements UserAPI.UserAPISoap.EndModifyUserProperties
            Return MyBase.Channel.EndModifyUserProperties(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndModifyUserProperties(ByVal result As System.IAsyncResult) As UserAPI.eAlentejoAPIResultCode
            Dim retVal As UserAPI.ModifyUserPropertiesResponse = CType(Me,UserAPI.UserAPISoap).EndModifyUserProperties(result)
            Return retVal.Body.ModifyUserPropertiesResult
        End Function
        
        Private Function OnBeginModifyUserProperties(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim SessionToken As String = CType(inValues(0),String)
            Dim NewProperties As UserAPI.cSMT_ATJ_User = CType(inValues(1),UserAPI.cSMT_ATJ_User)
            Return Me.BeginModifyUserProperties(SessionToken, NewProperties, callback, asyncState)
        End Function
        
        Private Function OnEndModifyUserProperties(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As UserAPI.eAlentejoAPIResultCode = Me.EndModifyUserProperties(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnModifyUserPropertiesCompleted(ByVal state As Object)
            If (Not (Me.ModifyUserPropertiesCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ModifyUserPropertiesCompleted(Me, New ModifyUserPropertiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ModifyUserPropertiesAsync(ByVal SessionToken As String, ByVal NewProperties As UserAPI.cSMT_ATJ_User)
            Me.ModifyUserPropertiesAsync(SessionToken, NewProperties, Nothing)
        End Sub
        
        Public Overloads Sub ModifyUserPropertiesAsync(ByVal SessionToken As String, ByVal NewProperties As UserAPI.cSMT_ATJ_User, ByVal userState As Object)
            If (Me.onBeginModifyUserPropertiesDelegate Is Nothing) Then
                Me.onBeginModifyUserPropertiesDelegate = AddressOf Me.OnBeginModifyUserProperties
            End If
            If (Me.onEndModifyUserPropertiesDelegate Is Nothing) Then
                Me.onEndModifyUserPropertiesDelegate = AddressOf Me.OnEndModifyUserProperties
            End If
            If (Me.onModifyUserPropertiesCompletedDelegate Is Nothing) Then
                Me.onModifyUserPropertiesCompletedDelegate = AddressOf Me.OnModifyUserPropertiesCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginModifyUserPropertiesDelegate, New Object() {SessionToken, NewProperties}, Me.onEndModifyUserPropertiesDelegate, Me.onModifyUserPropertiesCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_UsernameExists(ByVal request As UserAPI.UsernameExistsRequest) As UserAPI.UsernameExistsResponse Implements UserAPI.UserAPISoap.UsernameExists
            Return MyBase.Channel.UsernameExists(request)
        End Function
        
        Public Function UsernameExists(ByVal Username As String, ByRef outExists As Boolean) As UserAPI.eAlentejoAPIResultCode
            Dim inValue As UserAPI.UsernameExistsRequest = New UserAPI.UsernameExistsRequest()
            inValue.Body = New UserAPI.UsernameExistsRequestBody()
            inValue.Body.Username = Username
            inValue.Body.outExists = outExists
            Dim retVal As UserAPI.UsernameExistsResponse = CType(Me,UserAPI.UserAPISoap).UsernameExists(inValue)
            outExists = retVal.Body.outExists
            Return retVal.Body.UsernameExistsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_BeginUsernameExists(ByVal request As UserAPI.UsernameExistsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserAPI.UserAPISoap.BeginUsernameExists
            Return MyBase.Channel.BeginUsernameExists(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginUsernameExists(ByVal Username As String, ByVal outExists As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As UserAPI.UsernameExistsRequest = New UserAPI.UsernameExistsRequest()
            inValue.Body = New UserAPI.UsernameExistsRequestBody()
            inValue.Body.Username = Username
            inValue.Body.outExists = outExists
            Return CType(Me,UserAPI.UserAPISoap).BeginUsernameExists(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_EndUsernameExists(ByVal result As System.IAsyncResult) As UserAPI.UsernameExistsResponse Implements UserAPI.UserAPISoap.EndUsernameExists
            Return MyBase.Channel.EndUsernameExists(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndUsernameExists(ByVal result As System.IAsyncResult, <System.Runtime.InteropServices.OutAttribute()> ByRef outExists As Boolean) As UserAPI.eAlentejoAPIResultCode
            Dim retVal As UserAPI.UsernameExistsResponse = CType(Me,UserAPI.UserAPISoap).EndUsernameExists(result)
            outExists = retVal.Body.outExists
            Return retVal.Body.UsernameExistsResult
        End Function
        
        Private Function OnBeginUsernameExists(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Username As String = CType(inValues(0),String)
            Dim outExists As Boolean = CType(inValues(1),Boolean)
            Return Me.BeginUsernameExists(Username, outExists, callback, asyncState)
        End Function
        
        Private Function OnEndUsernameExists(ByVal result As System.IAsyncResult) As Object()
            Dim outExists As Boolean = Me.GetDefaultValueForInitialization(Of Boolean)
            Dim retVal As UserAPI.eAlentejoAPIResultCode = Me.EndUsernameExists(result, outExists)
            Return New Object() {outExists, retVal}
        End Function
        
        Private Sub OnUsernameExistsCompleted(ByVal state As Object)
            If (Not (Me.UsernameExistsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent UsernameExistsCompleted(Me, New UsernameExistsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub UsernameExistsAsync(ByVal Username As String, ByVal outExists As Boolean)
            Me.UsernameExistsAsync(Username, outExists, Nothing)
        End Sub
        
        Public Overloads Sub UsernameExistsAsync(ByVal Username As String, ByVal outExists As Boolean, ByVal userState As Object)
            If (Me.onBeginUsernameExistsDelegate Is Nothing) Then
                Me.onBeginUsernameExistsDelegate = AddressOf Me.OnBeginUsernameExists
            End If
            If (Me.onEndUsernameExistsDelegate Is Nothing) Then
                Me.onEndUsernameExistsDelegate = AddressOf Me.OnEndUsernameExists
            End If
            If (Me.onUsernameExistsCompletedDelegate Is Nothing) Then
                Me.onUsernameExistsCompletedDelegate = AddressOf Me.OnUsernameExistsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginUsernameExistsDelegate, New Object() {Username, outExists}, Me.onEndUsernameExistsDelegate, Me.onUsernameExistsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_Signup(ByVal request As UserAPI.SignupRequest) As UserAPI.SignupResponse Implements UserAPI.UserAPISoap.Signup
            Return MyBase.Channel.Signup(request)
        End Function
        
        Public Function Signup(ByVal User As UserAPI.cSMT_ATJ_User, ByRef outNewUserId As String) As UserAPI.eAlentejoAPIResultCode
            Dim inValue As UserAPI.SignupRequest = New UserAPI.SignupRequest()
            inValue.Body = New UserAPI.SignupRequestBody()
            inValue.Body.User = User
            inValue.Body.outNewUserId = outNewUserId
            Dim retVal As UserAPI.SignupResponse = CType(Me,UserAPI.UserAPISoap).Signup(inValue)
            outNewUserId = retVal.Body.outNewUserId
            Return retVal.Body.SignupResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_BeginSignup(ByVal request As UserAPI.SignupRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserAPI.UserAPISoap.BeginSignup
            Return MyBase.Channel.BeginSignup(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSignup(ByVal User As UserAPI.cSMT_ATJ_User, ByVal outNewUserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As UserAPI.SignupRequest = New UserAPI.SignupRequest()
            inValue.Body = New UserAPI.SignupRequestBody()
            inValue.Body.User = User
            inValue.Body.outNewUserId = outNewUserId
            Return CType(Me,UserAPI.UserAPISoap).BeginSignup(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserAPI_UserAPISoap_EndSignup(ByVal result As System.IAsyncResult) As UserAPI.SignupResponse Implements UserAPI.UserAPISoap.EndSignup
            Return MyBase.Channel.EndSignup(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndSignup(ByVal result As System.IAsyncResult, <System.Runtime.InteropServices.OutAttribute()> ByRef outNewUserId As String) As UserAPI.eAlentejoAPIResultCode
            Dim retVal As UserAPI.SignupResponse = CType(Me,UserAPI.UserAPISoap).EndSignup(result)
            outNewUserId = retVal.Body.outNewUserId
            Return retVal.Body.SignupResult
        End Function
        
        Private Function OnBeginSignup(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim User As UserAPI.cSMT_ATJ_User = CType(inValues(0),UserAPI.cSMT_ATJ_User)
            Dim outNewUserId As String = CType(inValues(1),String)
            Return Me.BeginSignup(User, outNewUserId, callback, asyncState)
        End Function
        
        Private Function OnEndSignup(ByVal result As System.IAsyncResult) As Object()
            Dim outNewUserId As String = Me.GetDefaultValueForInitialization(Of String)
            Dim retVal As UserAPI.eAlentejoAPIResultCode = Me.EndSignup(result, outNewUserId)
            Return New Object() {outNewUserId, retVal}
        End Function
        
        Private Sub OnSignupCompleted(ByVal state As Object)
            If (Not (Me.SignupCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SignupCompleted(Me, New SignupCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SignupAsync(ByVal User As UserAPI.cSMT_ATJ_User, ByVal outNewUserId As String)
            Me.SignupAsync(User, outNewUserId, Nothing)
        End Sub
        
        Public Overloads Sub SignupAsync(ByVal User As UserAPI.cSMT_ATJ_User, ByVal outNewUserId As String, ByVal userState As Object)
            If (Me.onBeginSignupDelegate Is Nothing) Then
                Me.onBeginSignupDelegate = AddressOf Me.OnBeginSignup
            End If
            If (Me.onEndSignupDelegate Is Nothing) Then
                Me.onEndSignupDelegate = AddressOf Me.OnEndSignup
            End If
            If (Me.onSignupCompletedDelegate Is Nothing) Then
                Me.onSignupCompletedDelegate = AddressOf Me.OnSignupCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSignupDelegate, New Object() {User, outNewUserId}, Me.onEndSignupDelegate, Me.onSignupCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
