'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
'
Namespace AlentejoAuthService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="cSMT_ATJ_User", [Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class cSMT_ATJ_User
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private SCHEMA_VERSIONField As String
        
        Private IdField As String
        
        Private Created_UTCTicksField As String
        
        Private LastLogin_UTCTicksField As String
        
        Private Balance_EncryptedField As String
        
        Private UsernameField As String
        
        Private PasswordHashField As String
        
        Private TimezoneField As String
        
        Private LastLoginIpAddressField As String
        
        Private FirstNameField As String
        
        Private LastNameField As String
        
        Private CompanyField As String
        
        Private Address1Field As String
        
        Private Address2Field As String
        
        Private Address3Field As String
        
        Private CityField As String
        
        Private StateField As String
        
        Private PostalCodeField As String
        
        Private CountryField As String
        
        Private EmailAddressField As String
        
        Private PhoneOfficeField As String
        
        Private PhoneMobileField As String
        
        Private WebsiteField As String
        
        Private PayPalAccountEmailAddressField As String
        
        Private EmailNotificationLevelField As String
        
        Private NumberOfCoresField As String
        
        Private RenderLevelsField As String
        
        Private MaxRenderingTimeField As String
        
        Private MaxCostField As String
        
        Private OutputTypeField As String
        
        Private RenderEngineField As String
        
        Private AccountStatusField As String
        
        Private AccountTypeField As String
        
        Private BillingTypeField As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SCHEMA_VERSION() As String
            Get
                Return Me.SCHEMA_VERSIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SCHEMA_VERSIONField, value) <> true) Then
                    Me.SCHEMA_VERSIONField = value
                    Me.RaisePropertyChanged("SCHEMA_VERSION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Created_UTCTicks() As String
            Get
                Return Me.Created_UTCTicksField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Created_UTCTicksField, value) <> true) Then
                    Me.Created_UTCTicksField = value
                    Me.RaisePropertyChanged("Created_UTCTicks")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property LastLogin_UTCTicks() As String
            Get
                Return Me.LastLogin_UTCTicksField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastLogin_UTCTicksField, value) <> true) Then
                    Me.LastLogin_UTCTicksField = value
                    Me.RaisePropertyChanged("LastLogin_UTCTicks")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Balance_Encrypted() As String
            Get
                Return Me.Balance_EncryptedField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Balance_EncryptedField, value) <> true) Then
                    Me.Balance_EncryptedField = value
                    Me.RaisePropertyChanged("Balance_Encrypted")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property PasswordHash() As String
            Get
                Return Me.PasswordHashField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordHashField, value) <> true) Then
                    Me.PasswordHashField = value
                    Me.RaisePropertyChanged("PasswordHash")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Timezone() As String
            Get
                Return Me.TimezoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimezoneField, value) <> true) Then
                    Me.TimezoneField = value
                    Me.RaisePropertyChanged("Timezone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property LastLoginIpAddress() As String
            Get
                Return Me.LastLoginIpAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastLoginIpAddressField, value) <> true) Then
                    Me.LastLoginIpAddressField = value
                    Me.RaisePropertyChanged("LastLoginIpAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property Address1() As String
            Get
                Return Me.Address1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Address1Field, value) <> true) Then
                    Me.Address1Field = value
                    Me.RaisePropertyChanged("Address1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property Address2() As String
            Get
                Return Me.Address2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Address2Field, value) <> true) Then
                    Me.Address2Field = value
                    Me.RaisePropertyChanged("Address2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property Address3() As String
            Get
                Return Me.Address3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Address3Field, value) <> true) Then
                    Me.Address3Field = value
                    Me.RaisePropertyChanged("Address3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property PostalCode() As String
            Get
                Return Me.PostalCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostalCodeField, value) <> true) Then
                    Me.PostalCodeField = value
                    Me.RaisePropertyChanged("PostalCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Property Country() As String
            Get
                Return Me.CountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryField, value) <> true) Then
                    Me.CountryField = value
                    Me.RaisePropertyChanged("Country")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=19)>  _
        Public Property EmailAddress() As String
            Get
                Return Me.EmailAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailAddressField, value) <> true) Then
                    Me.EmailAddressField = value
                    Me.RaisePropertyChanged("EmailAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=20)>  _
        Public Property PhoneOffice() As String
            Get
                Return Me.PhoneOfficeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneOfficeField, value) <> true) Then
                    Me.PhoneOfficeField = value
                    Me.RaisePropertyChanged("PhoneOffice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=21)>  _
        Public Property PhoneMobile() As String
            Get
                Return Me.PhoneMobileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneMobileField, value) <> true) Then
                    Me.PhoneMobileField = value
                    Me.RaisePropertyChanged("PhoneMobile")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public Property Website() As String
            Get
                Return Me.WebsiteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WebsiteField, value) <> true) Then
                    Me.WebsiteField = value
                    Me.RaisePropertyChanged("Website")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=23)>  _
        Public Property PayPalAccountEmailAddress() As String
            Get
                Return Me.PayPalAccountEmailAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PayPalAccountEmailAddressField, value) <> true) Then
                    Me.PayPalAccountEmailAddressField = value
                    Me.RaisePropertyChanged("PayPalAccountEmailAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=24)>  _
        Public Property EmailNotificationLevel() As String
            Get
                Return Me.EmailNotificationLevelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailNotificationLevelField, value) <> true) Then
                    Me.EmailNotificationLevelField = value
                    Me.RaisePropertyChanged("EmailNotificationLevel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=25)>  _
        Public Property NumberOfCores() As String
            Get
                Return Me.NumberOfCoresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumberOfCoresField, value) <> true) Then
                    Me.NumberOfCoresField = value
                    Me.RaisePropertyChanged("NumberOfCores")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=26)>  _
        Public Property RenderLevels() As String
            Get
                Return Me.RenderLevelsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RenderLevelsField, value) <> true) Then
                    Me.RenderLevelsField = value
                    Me.RaisePropertyChanged("RenderLevels")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=27)>  _
        Public Property MaxRenderingTime() As String
            Get
                Return Me.MaxRenderingTimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MaxRenderingTimeField, value) <> true) Then
                    Me.MaxRenderingTimeField = value
                    Me.RaisePropertyChanged("MaxRenderingTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=28)>  _
        Public Property MaxCost() As String
            Get
                Return Me.MaxCostField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MaxCostField, value) <> true) Then
                    Me.MaxCostField = value
                    Me.RaisePropertyChanged("MaxCost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=29)>  _
        Public Property OutputType() As String
            Get
                Return Me.OutputTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OutputTypeField, value) <> true) Then
                    Me.OutputTypeField = value
                    Me.RaisePropertyChanged("OutputType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=30)>  _
        Public Property RenderEngine() As String
            Get
                Return Me.RenderEngineField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RenderEngineField, value) <> true) Then
                    Me.RenderEngineField = value
                    Me.RaisePropertyChanged("RenderEngine")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=31)>  _
        Public Property AccountStatus() As String
            Get
                Return Me.AccountStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountStatusField, value) <> true) Then
                    Me.AccountStatusField = value
                    Me.RaisePropertyChanged("AccountStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=32)>  _
        Public Property AccountType() As String
            Get
                Return Me.AccountTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccountTypeField, value) <> true) Then
                    Me.AccountTypeField = value
                    Me.RaisePropertyChanged("AccountType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=33)>  _
        Public Property BillingType() As String
            Get
                Return Me.BillingTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BillingTypeField, value) <> true) Then
                    Me.BillingTypeField = value
                    Me.RaisePropertyChanged("BillingType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="cSMT_ATJ_User_Lite", [Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class cSMT_ATJ_User_Lite
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private IdField As String
        
        Private UsernameField As String
        
        Private FirstNameField As String
        
        Private LastNameField As String
        
        Private CompanyField As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://rm.seqmt.com/", ConfigurationName:="AlentejoAuthService.AlentejoAuthServiceSoap")>  _
    Public Interface AlentejoAuthServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://rm.seqmt.com/Login", ReplyAction:="*")>  _
        Function BeginLogin(ByVal request As AlentejoAuthService.LoginRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndLogin(ByVal result As System.IAsyncResult) As AlentejoAuthService.LoginResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://rm.seqmt.com/Logout", ReplyAction:="*")>  _
        Function BeginLogout(ByVal request As AlentejoAuthService.LogoutRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndLogout(ByVal result As System.IAsyncResult) As AlentejoAuthService.LogoutResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://rm.seqmt.com/UsernameExists", ReplyAction:="*")>  _
        Function BeginUsernameExists(ByVal request As AlentejoAuthService.UsernameExistsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndUsernameExists(ByVal result As System.IAsyncResult) As AlentejoAuthService.UsernameExistsResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://rm.seqmt.com/SaveUser", ReplyAction:="*")>  _
        Function BeginSaveUser(ByVal request As AlentejoAuthService.SaveUserRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSaveUser(ByVal result As System.IAsyncResult) As AlentejoAuthService.SaveUserResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://rm.seqmt.com/GetClientIP", ReplyAction:="*")>  _
        Function BeginGetClientIP(ByVal request As AlentejoAuthService.GetClientIPRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetClientIP(ByVal result As System.IAsyncResult) As AlentejoAuthService.GetClientIPResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://rm.seqmt.com/GetUserInfoLite", ReplyAction:="*")>  _
        Function BeginGetUserInfoLite(ByVal request As AlentejoAuthService.GetUserInfoLiteRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetUserInfoLite(ByVal result As System.IAsyncResult) As AlentejoAuthService.GetUserInfoLiteResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://rm.seqmt.com/GetUserBalance", ReplyAction:="*")>  _
        Function BeginGetUserBalance(ByVal request As AlentejoAuthService.GetUserBalanceRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetUserBalance(ByVal result As System.IAsyncResult) As AlentejoAuthService.GetUserBalanceResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Login", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.LoginRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.LoginRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class LoginRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public PasswordHash As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Username As String, ByVal PasswordHash As String)
            MyBase.New
            Me.Username = Username
            Me.PasswordHash = PasswordHash
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoginResponse", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.LoginResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.LoginResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class LoginResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoginResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoginResult As String)
            MyBase.New
            Me.LoginResult = LoginResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogoutRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Logout", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.LogoutRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.LogoutRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class LogoutRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SessionId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SessionId As String)
            MyBase.New
            Me.SessionId = SessionId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogoutResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LogoutResponse", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.LogoutResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.LogoutResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class LogoutResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UsernameExistsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UsernameExists", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.UsernameExistsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.UsernameExistsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class UsernameExistsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Username As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Username As String)
            MyBase.New
            Me.Username = Username
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UsernameExistsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UsernameExistsResponse", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.UsernameExistsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.UsernameExistsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class UsernameExistsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public UsernameExistsResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UsernameExistsResult As Boolean)
            MyBase.New
            Me.UsernameExistsResult = UsernameExistsResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SaveUserRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SaveUser", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.SaveUserRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.SaveUserRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class SaveUserRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SessionToken As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public User As AlentejoAuthService.cSMT_ATJ_User
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SessionToken As String, ByVal User As AlentejoAuthService.cSMT_ATJ_User)
            MyBase.New
            Me.SessionToken = SessionToken
            Me.User = User
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SaveUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SaveUserResponse", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.SaveUserResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.SaveUserResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class SaveUserResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SaveUserResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SaveUserResult As String)
            MyBase.New
            Me.SaveUserResult = SaveUserResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetClientIPRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetClientIP", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.GetClientIPRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.GetClientIPRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetClientIPRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetClientIPResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetClientIPResponse", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.GetClientIPResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.GetClientIPResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class GetClientIPResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetClientIPResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetClientIPResult As String)
            MyBase.New
            Me.GetClientIPResult = GetClientIPResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUserInfoLiteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserInfoLite", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.GetUserInfoLiteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.GetUserInfoLiteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class GetUserInfoLiteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Username As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Username As String)
            MyBase.New
            Me.Username = Username
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUserInfoLiteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserInfoLiteResponse", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.GetUserInfoLiteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.GetUserInfoLiteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class GetUserInfoLiteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUserInfoLiteResult As AlentejoAuthService.cSMT_ATJ_User_Lite
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUserInfoLiteResult As AlentejoAuthService.cSMT_ATJ_User_Lite)
            MyBase.New
            Me.GetUserInfoLiteResult = GetUserInfoLiteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUserBalanceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserBalance", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.GetUserBalanceRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.GetUserBalanceRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class GetUserBalanceRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SessionToken As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public UserId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SessionToken As String, ByVal UserId As String)
            MyBase.New
            Me.SessionToken = SessionToken
            Me.UserId = UserId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUserBalanceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserBalanceResponse", [Namespace]:="http://rm.seqmt.com/", Order:=0)>  _
        Public Body As AlentejoAuthService.GetUserBalanceResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AlentejoAuthService.GetUserBalanceResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://rm.seqmt.com/")>  _
    Partial Public Class GetUserBalanceResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetUserBalanceResult As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUserBalanceResult As Double)
            MyBase.New
            Me.GetUserBalanceResult = GetUserBalanceResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface AlentejoAuthServiceSoapChannel
        Inherits AlentejoAuthService.AlentejoAuthServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UsernameExistsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SaveUserCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetClientIPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetUserInfoLiteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As AlentejoAuthService.cSMT_ATJ_User_Lite
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AlentejoAuthService.cSMT_ATJ_User_Lite)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetUserBalanceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Double
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AlentejoAuthServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of AlentejoAuthService.AlentejoAuthServiceSoap)
        Implements AlentejoAuthService.AlentejoAuthServiceSoap
        
        Private onBeginLoginDelegate As BeginOperationDelegate
        
        Private onEndLoginDelegate As EndOperationDelegate
        
        Private onLoginCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginLogoutDelegate As BeginOperationDelegate
        
        Private onEndLogoutDelegate As EndOperationDelegate
        
        Private onLogoutCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginUsernameExistsDelegate As BeginOperationDelegate
        
        Private onEndUsernameExistsDelegate As EndOperationDelegate
        
        Private onUsernameExistsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSaveUserDelegate As BeginOperationDelegate
        
        Private onEndSaveUserDelegate As EndOperationDelegate
        
        Private onSaveUserCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetClientIPDelegate As BeginOperationDelegate
        
        Private onEndGetClientIPDelegate As EndOperationDelegate
        
        Private onGetClientIPCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetUserInfoLiteDelegate As BeginOperationDelegate
        
        Private onEndGetUserInfoLiteDelegate As EndOperationDelegate
        
        Private onGetUserInfoLiteCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetUserBalanceDelegate As BeginOperationDelegate
        
        Private onEndGetUserBalanceDelegate As EndOperationDelegate
        
        Private onGetUserBalanceCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event LoginCompleted As System.EventHandler(Of LoginCompletedEventArgs)
        
        Public Event LogoutCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event UsernameExistsCompleted As System.EventHandler(Of UsernameExistsCompletedEventArgs)
        
        Public Event SaveUserCompleted As System.EventHandler(Of SaveUserCompletedEventArgs)
        
        Public Event GetClientIPCompleted As System.EventHandler(Of GetClientIPCompletedEventArgs)
        
        Public Event GetUserInfoLiteCompleted As System.EventHandler(Of GetUserInfoLiteCompletedEventArgs)
        
        Public Event GetUserBalanceCompleted As System.EventHandler(Of GetUserBalanceCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_BeginLogin(ByVal request As AlentejoAuthService.LoginRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginLogin
            Return MyBase.Channel.BeginLogin(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginLogin(ByVal Username As String, ByVal PasswordHash As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As AlentejoAuthService.LoginRequest = New AlentejoAuthService.LoginRequest()
            inValue.Body = New AlentejoAuthService.LoginRequestBody()
            inValue.Body.Username = Username
            inValue.Body.PasswordHash = PasswordHash
            Return CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).BeginLogin(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_EndLogin(ByVal result As System.IAsyncResult) As AlentejoAuthService.LoginResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndLogin
            Return MyBase.Channel.EndLogin(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndLogin(ByVal result As System.IAsyncResult) As String
            Dim retVal As AlentejoAuthService.LoginResponse = CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).EndLogin(result)
            Return retVal.Body.LoginResult
        End Function
        
        Private Function OnBeginLogin(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Username As String = CType(inValues(0),String)
            Dim PasswordHash As String = CType(inValues(1),String)
            Return Me.BeginLogin(Username, PasswordHash, callback, asyncState)
        End Function
        
        Private Function OnEndLogin(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndLogin(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnLoginCompleted(ByVal state As Object)
            If (Not (Me.LoginCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent LoginCompleted(Me, New LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub LoginAsync(ByVal Username As String, ByVal PasswordHash As String)
            Me.LoginAsync(Username, PasswordHash, Nothing)
        End Sub
        
        Public Overloads Sub LoginAsync(ByVal Username As String, ByVal PasswordHash As String, ByVal userState As Object)
            If (Me.onBeginLoginDelegate Is Nothing) Then
                Me.onBeginLoginDelegate = AddressOf Me.OnBeginLogin
            End If
            If (Me.onEndLoginDelegate Is Nothing) Then
                Me.onEndLoginDelegate = AddressOf Me.OnEndLogin
            End If
            If (Me.onLoginCompletedDelegate Is Nothing) Then
                Me.onLoginCompletedDelegate = AddressOf Me.OnLoginCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginLoginDelegate, New Object() {Username, PasswordHash}, Me.onEndLoginDelegate, Me.onLoginCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_BeginLogout(ByVal request As AlentejoAuthService.LogoutRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginLogout
            Return MyBase.Channel.BeginLogout(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginLogout(ByVal SessionId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As AlentejoAuthService.LogoutRequest = New AlentejoAuthService.LogoutRequest()
            inValue.Body = New AlentejoAuthService.LogoutRequestBody()
            inValue.Body.SessionId = SessionId
            Return CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).BeginLogout(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_EndLogout(ByVal result As System.IAsyncResult) As AlentejoAuthService.LogoutResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndLogout
            Return MyBase.Channel.EndLogout(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Sub EndLogout(ByVal result As System.IAsyncResult)
            Dim retVal As AlentejoAuthService.LogoutResponse = CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).EndLogout(result)
        End Sub
        
        Private Function OnBeginLogout(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim SessionId As String = CType(inValues(0),String)
            Return Me.BeginLogout(SessionId, callback, asyncState)
        End Function
        
        Private Function OnEndLogout(ByVal result As System.IAsyncResult) As Object()
            Me.EndLogout(result)
            Return Nothing
        End Function
        
        Private Sub OnLogoutCompleted(ByVal state As Object)
            If (Not (Me.LogoutCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent LogoutCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub LogoutAsync(ByVal SessionId As String)
            Me.LogoutAsync(SessionId, Nothing)
        End Sub
        
        Public Overloads Sub LogoutAsync(ByVal SessionId As String, ByVal userState As Object)
            If (Me.onBeginLogoutDelegate Is Nothing) Then
                Me.onBeginLogoutDelegate = AddressOf Me.OnBeginLogout
            End If
            If (Me.onEndLogoutDelegate Is Nothing) Then
                Me.onEndLogoutDelegate = AddressOf Me.OnEndLogout
            End If
            If (Me.onLogoutCompletedDelegate Is Nothing) Then
                Me.onLogoutCompletedDelegate = AddressOf Me.OnLogoutCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginLogoutDelegate, New Object() {SessionId}, Me.onEndLogoutDelegate, Me.onLogoutCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_BeginUsernameExists(ByVal request As AlentejoAuthService.UsernameExistsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginUsernameExists
            Return MyBase.Channel.BeginUsernameExists(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginUsernameExists(ByVal Username As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As AlentejoAuthService.UsernameExistsRequest = New AlentejoAuthService.UsernameExistsRequest()
            inValue.Body = New AlentejoAuthService.UsernameExistsRequestBody()
            inValue.Body.Username = Username
            Return CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).BeginUsernameExists(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_EndUsernameExists(ByVal result As System.IAsyncResult) As AlentejoAuthService.UsernameExistsResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndUsernameExists
            Return MyBase.Channel.EndUsernameExists(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndUsernameExists(ByVal result As System.IAsyncResult) As Boolean
            Dim retVal As AlentejoAuthService.UsernameExistsResponse = CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).EndUsernameExists(result)
            Return retVal.Body.UsernameExistsResult
        End Function
        
        Private Function OnBeginUsernameExists(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Username As String = CType(inValues(0),String)
            Return Me.BeginUsernameExists(Username, callback, asyncState)
        End Function
        
        Private Function OnEndUsernameExists(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndUsernameExists(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnUsernameExistsCompleted(ByVal state As Object)
            If (Not (Me.UsernameExistsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent UsernameExistsCompleted(Me, New UsernameExistsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub UsernameExistsAsync(ByVal Username As String)
            Me.UsernameExistsAsync(Username, Nothing)
        End Sub
        
        Public Overloads Sub UsernameExistsAsync(ByVal Username As String, ByVal userState As Object)
            If (Me.onBeginUsernameExistsDelegate Is Nothing) Then
                Me.onBeginUsernameExistsDelegate = AddressOf Me.OnBeginUsernameExists
            End If
            If (Me.onEndUsernameExistsDelegate Is Nothing) Then
                Me.onEndUsernameExistsDelegate = AddressOf Me.OnEndUsernameExists
            End If
            If (Me.onUsernameExistsCompletedDelegate Is Nothing) Then
                Me.onUsernameExistsCompletedDelegate = AddressOf Me.OnUsernameExistsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginUsernameExistsDelegate, New Object() {Username}, Me.onEndUsernameExistsDelegate, Me.onUsernameExistsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_BeginSaveUser(ByVal request As AlentejoAuthService.SaveUserRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginSaveUser
            Return MyBase.Channel.BeginSaveUser(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginSaveUser(ByVal SessionToken As String, ByVal User As AlentejoAuthService.cSMT_ATJ_User, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As AlentejoAuthService.SaveUserRequest = New AlentejoAuthService.SaveUserRequest()
            inValue.Body = New AlentejoAuthService.SaveUserRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.User = User
            Return CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).BeginSaveUser(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_EndSaveUser(ByVal result As System.IAsyncResult) As AlentejoAuthService.SaveUserResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndSaveUser
            Return MyBase.Channel.EndSaveUser(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndSaveUser(ByVal result As System.IAsyncResult) As String
            Dim retVal As AlentejoAuthService.SaveUserResponse = CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).EndSaveUser(result)
            Return retVal.Body.SaveUserResult
        End Function
        
        Private Function OnBeginSaveUser(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim SessionToken As String = CType(inValues(0),String)
            Dim User As AlentejoAuthService.cSMT_ATJ_User = CType(inValues(1),AlentejoAuthService.cSMT_ATJ_User)
            Return Me.BeginSaveUser(SessionToken, User, callback, asyncState)
        End Function
        
        Private Function OnEndSaveUser(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndSaveUser(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnSaveUserCompleted(ByVal state As Object)
            If (Not (Me.SaveUserCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SaveUserCompleted(Me, New SaveUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SaveUserAsync(ByVal SessionToken As String, ByVal User As AlentejoAuthService.cSMT_ATJ_User)
            Me.SaveUserAsync(SessionToken, User, Nothing)
        End Sub
        
        Public Overloads Sub SaveUserAsync(ByVal SessionToken As String, ByVal User As AlentejoAuthService.cSMT_ATJ_User, ByVal userState As Object)
            If (Me.onBeginSaveUserDelegate Is Nothing) Then
                Me.onBeginSaveUserDelegate = AddressOf Me.OnBeginSaveUser
            End If
            If (Me.onEndSaveUserDelegate Is Nothing) Then
                Me.onEndSaveUserDelegate = AddressOf Me.OnEndSaveUser
            End If
            If (Me.onSaveUserCompletedDelegate Is Nothing) Then
                Me.onSaveUserCompletedDelegate = AddressOf Me.OnSaveUserCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSaveUserDelegate, New Object() {SessionToken, User}, Me.onEndSaveUserDelegate, Me.onSaveUserCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_BeginGetClientIP(ByVal request As AlentejoAuthService.GetClientIPRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginGetClientIP
            Return MyBase.Channel.BeginGetClientIP(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginGetClientIP(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As AlentejoAuthService.GetClientIPRequest = New AlentejoAuthService.GetClientIPRequest()
            inValue.Body = New AlentejoAuthService.GetClientIPRequestBody()
            Return CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).BeginGetClientIP(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_EndGetClientIP(ByVal result As System.IAsyncResult) As AlentejoAuthService.GetClientIPResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndGetClientIP
            Return MyBase.Channel.EndGetClientIP(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndGetClientIP(ByVal result As System.IAsyncResult) As String
            Dim retVal As AlentejoAuthService.GetClientIPResponse = CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).EndGetClientIP(result)
            Return retVal.Body.GetClientIPResult
        End Function
        
        Private Function OnBeginGetClientIP(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginGetClientIP(callback, asyncState)
        End Function
        
        Private Function OnEndGetClientIP(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndGetClientIP(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetClientIPCompleted(ByVal state As Object)
            If (Not (Me.GetClientIPCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetClientIPCompleted(Me, New GetClientIPCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetClientIPAsync()
            Me.GetClientIPAsync(Nothing)
        End Sub
        
        Public Overloads Sub GetClientIPAsync(ByVal userState As Object)
            If (Me.onBeginGetClientIPDelegate Is Nothing) Then
                Me.onBeginGetClientIPDelegate = AddressOf Me.OnBeginGetClientIP
            End If
            If (Me.onEndGetClientIPDelegate Is Nothing) Then
                Me.onEndGetClientIPDelegate = AddressOf Me.OnEndGetClientIP
            End If
            If (Me.onGetClientIPCompletedDelegate Is Nothing) Then
                Me.onGetClientIPCompletedDelegate = AddressOf Me.OnGetClientIPCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetClientIPDelegate, Nothing, Me.onEndGetClientIPDelegate, Me.onGetClientIPCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_BeginGetUserInfoLite(ByVal request As AlentejoAuthService.GetUserInfoLiteRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginGetUserInfoLite
            Return MyBase.Channel.BeginGetUserInfoLite(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginGetUserInfoLite(ByVal Username As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As AlentejoAuthService.GetUserInfoLiteRequest = New AlentejoAuthService.GetUserInfoLiteRequest()
            inValue.Body = New AlentejoAuthService.GetUserInfoLiteRequestBody()
            inValue.Body.Username = Username
            Return CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).BeginGetUserInfoLite(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_EndGetUserInfoLite(ByVal result As System.IAsyncResult) As AlentejoAuthService.GetUserInfoLiteResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndGetUserInfoLite
            Return MyBase.Channel.EndGetUserInfoLite(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndGetUserInfoLite(ByVal result As System.IAsyncResult) As AlentejoAuthService.cSMT_ATJ_User_Lite
            Dim retVal As AlentejoAuthService.GetUserInfoLiteResponse = CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).EndGetUserInfoLite(result)
            Return retVal.Body.GetUserInfoLiteResult
        End Function
        
        Private Function OnBeginGetUserInfoLite(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Username As String = CType(inValues(0),String)
            Return Me.BeginGetUserInfoLite(Username, callback, asyncState)
        End Function
        
        Private Function OnEndGetUserInfoLite(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As AlentejoAuthService.cSMT_ATJ_User_Lite = Me.EndGetUserInfoLite(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetUserInfoLiteCompleted(ByVal state As Object)
            If (Not (Me.GetUserInfoLiteCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetUserInfoLiteCompleted(Me, New GetUserInfoLiteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetUserInfoLiteAsync(ByVal Username As String)
            Me.GetUserInfoLiteAsync(Username, Nothing)
        End Sub
        
        Public Overloads Sub GetUserInfoLiteAsync(ByVal Username As String, ByVal userState As Object)
            If (Me.onBeginGetUserInfoLiteDelegate Is Nothing) Then
                Me.onBeginGetUserInfoLiteDelegate = AddressOf Me.OnBeginGetUserInfoLite
            End If
            If (Me.onEndGetUserInfoLiteDelegate Is Nothing) Then
                Me.onEndGetUserInfoLiteDelegate = AddressOf Me.OnEndGetUserInfoLite
            End If
            If (Me.onGetUserInfoLiteCompletedDelegate Is Nothing) Then
                Me.onGetUserInfoLiteCompletedDelegate = AddressOf Me.OnGetUserInfoLiteCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetUserInfoLiteDelegate, New Object() {Username}, Me.onEndGetUserInfoLiteDelegate, Me.onGetUserInfoLiteCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_BeginGetUserBalance(ByVal request As AlentejoAuthService.GetUserBalanceRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginGetUserBalance
            Return MyBase.Channel.BeginGetUserBalance(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginGetUserBalance(ByVal SessionToken As String, ByVal UserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As AlentejoAuthService.GetUserBalanceRequest = New AlentejoAuthService.GetUserBalanceRequest()
            inValue.Body = New AlentejoAuthService.GetUserBalanceRequestBody()
            inValue.Body.SessionToken = SessionToken
            inValue.Body.UserId = UserId
            Return CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).BeginGetUserBalance(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AlentejoAuthService_AlentejoAuthServiceSoap_EndGetUserBalance(ByVal result As System.IAsyncResult) As AlentejoAuthService.GetUserBalanceResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndGetUserBalance
            Return MyBase.Channel.EndGetUserBalance(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndGetUserBalance(ByVal result As System.IAsyncResult) As Double
            Dim retVal As AlentejoAuthService.GetUserBalanceResponse = CType(Me,AlentejoAuthService.AlentejoAuthServiceSoap).EndGetUserBalance(result)
            Return retVal.Body.GetUserBalanceResult
        End Function
        
        Private Function OnBeginGetUserBalance(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim SessionToken As String = CType(inValues(0),String)
            Dim UserId As String = CType(inValues(1),String)
            Return Me.BeginGetUserBalance(SessionToken, UserId, callback, asyncState)
        End Function
        
        Private Function OnEndGetUserBalance(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Double = Me.EndGetUserBalance(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetUserBalanceCompleted(ByVal state As Object)
            If (Not (Me.GetUserBalanceCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetUserBalanceCompleted(Me, New GetUserBalanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetUserBalanceAsync(ByVal SessionToken As String, ByVal UserId As String)
            Me.GetUserBalanceAsync(SessionToken, UserId, Nothing)
        End Sub
        
        Public Overloads Sub GetUserBalanceAsync(ByVal SessionToken As String, ByVal UserId As String, ByVal userState As Object)
            If (Me.onBeginGetUserBalanceDelegate Is Nothing) Then
                Me.onBeginGetUserBalanceDelegate = AddressOf Me.OnBeginGetUserBalance
            End If
            If (Me.onEndGetUserBalanceDelegate Is Nothing) Then
                Me.onEndGetUserBalanceDelegate = AddressOf Me.OnEndGetUserBalance
            End If
            If (Me.onGetUserBalanceCompletedDelegate Is Nothing) Then
                Me.onGetUserBalanceCompletedDelegate = AddressOf Me.OnGetUserBalanceCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetUserBalanceDelegate, New Object() {SessionToken, UserId}, Me.onEndGetUserBalanceDelegate, Me.onGetUserBalanceCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As AlentejoAuthService.AlentejoAuthServiceSoap
            Return New AlentejoAuthServiceSoapClientChannel(Me)
        End Function
        
        Private Class AlentejoAuthServiceSoapClientChannel
            Inherits ChannelBase(Of AlentejoAuthService.AlentejoAuthServiceSoap)
            Implements AlentejoAuthService.AlentejoAuthServiceSoap
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of AlentejoAuthService.AlentejoAuthServiceSoap))
                MyBase.New(client)
            End Sub
            
            Public Function BeginLogin(ByVal request As AlentejoAuthService.LoginRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginLogin
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("Login", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndLogin(ByVal result As System.IAsyncResult) As AlentejoAuthService.LoginResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndLogin
                Dim _args((0) - 1) As Object
                Dim _result As AlentejoAuthService.LoginResponse = CType(MyBase.EndInvoke("Login", _args, result),AlentejoAuthService.LoginResponse)
                Return _result
            End Function
            
            Public Function BeginLogout(ByVal request As AlentejoAuthService.LogoutRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginLogout
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("Logout", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndLogout(ByVal result As System.IAsyncResult) As AlentejoAuthService.LogoutResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndLogout
                Dim _args((0) - 1) As Object
                Dim _result As AlentejoAuthService.LogoutResponse = CType(MyBase.EndInvoke("Logout", _args, result),AlentejoAuthService.LogoutResponse)
                Return _result
            End Function
            
            Public Function BeginUsernameExists(ByVal request As AlentejoAuthService.UsernameExistsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginUsernameExists
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("UsernameExists", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndUsernameExists(ByVal result As System.IAsyncResult) As AlentejoAuthService.UsernameExistsResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndUsernameExists
                Dim _args((0) - 1) As Object
                Dim _result As AlentejoAuthService.UsernameExistsResponse = CType(MyBase.EndInvoke("UsernameExists", _args, result),AlentejoAuthService.UsernameExistsResponse)
                Return _result
            End Function
            
            Public Function BeginSaveUser(ByVal request As AlentejoAuthService.SaveUserRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginSaveUser
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("SaveUser", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndSaveUser(ByVal result As System.IAsyncResult) As AlentejoAuthService.SaveUserResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndSaveUser
                Dim _args((0) - 1) As Object
                Dim _result As AlentejoAuthService.SaveUserResponse = CType(MyBase.EndInvoke("SaveUser", _args, result),AlentejoAuthService.SaveUserResponse)
                Return _result
            End Function
            
            Public Function BeginGetClientIP(ByVal request As AlentejoAuthService.GetClientIPRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginGetClientIP
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetClientIP", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGetClientIP(ByVal result As System.IAsyncResult) As AlentejoAuthService.GetClientIPResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndGetClientIP
                Dim _args((0) - 1) As Object
                Dim _result As AlentejoAuthService.GetClientIPResponse = CType(MyBase.EndInvoke("GetClientIP", _args, result),AlentejoAuthService.GetClientIPResponse)
                Return _result
            End Function
            
            Public Function BeginGetUserInfoLite(ByVal request As AlentejoAuthService.GetUserInfoLiteRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginGetUserInfoLite
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetUserInfoLite", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGetUserInfoLite(ByVal result As System.IAsyncResult) As AlentejoAuthService.GetUserInfoLiteResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndGetUserInfoLite
                Dim _args((0) - 1) As Object
                Dim _result As AlentejoAuthService.GetUserInfoLiteResponse = CType(MyBase.EndInvoke("GetUserInfoLite", _args, result),AlentejoAuthService.GetUserInfoLiteResponse)
                Return _result
            End Function
            
            Public Function BeginGetUserBalance(ByVal request As AlentejoAuthService.GetUserBalanceRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AlentejoAuthService.AlentejoAuthServiceSoap.BeginGetUserBalance
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetUserBalance", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGetUserBalance(ByVal result As System.IAsyncResult) As AlentejoAuthService.GetUserBalanceResponse Implements AlentejoAuthService.AlentejoAuthServiceSoap.EndGetUserBalance
                Dim _args((0) - 1) As Object
                Dim _result As AlentejoAuthService.GetUserBalanceResponse = CType(MyBase.EndInvoke("GetUserBalance", _args, result),AlentejoAuthService.GetUserBalanceResponse)
                Return _result
            End Function
        End Class
    End Class
End Namespace
